/**
 * @file ctemplate.h
 * @brief Public API for the ctemplate library.
 *
 * ctemplate is a small, dependency-free growable string buffer used here as
 * a stand-in for "your real library". It exists to demonstrate the coding
 * conventions this template encourages:
 *
 *   - An opaque type (ctemplate_strbuf) so callers cannot depend on its
 *     internal layout, which keeps the ABI stable across releases.
 *   - A create/destroy pair that makes ownership explicit.
 *   - Enum-based status codes instead of magic numbers or errno.
 *   - const-correctness on every read-only parameter and return value.
 *   - A single export macro (CTEMPLATE_API), generated by CMake, so the
 *     same header works whether the library is built static or shared.
 *
 * Replace the contents of this header/src pair with your own API and keep
 * the same shape: public types and functions declared here, implementation
 * details kept in src/.
 */

#ifndef CTEMPLATE_CTEMPLATE_H
#define CTEMPLATE_CTEMPLATE_H

#include <stddef.h>

#include "ctemplate/export.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CTEMPLATE_VERSION_MAJOR 0
#define CTEMPLATE_VERSION_MINOR 1
#define CTEMPLATE_VERSION_PATCH 0

/** Opaque growable string buffer. */
typedef struct ctemplate_strbuf ctemplate_strbuf;

/** Status codes returned by fallible ctemplate_* functions. */
typedef enum ctemplate_status {
    CTEMPLATE_OK = 0,          /**< Success. */
    CTEMPLATE_ERR_INVALID_ARG, /**< A required argument was NULL or otherwise invalid. */
    CTEMPLATE_ERR_NOMEM        /**< A memory allocation failed. */
} ctemplate_status;

/**
 * @brief Create a new, empty string buffer.
 *
 * @param initial_capacity Number of bytes to pre-allocate (0 selects a
 *                          reasonable default). The buffer grows
 *                          automatically as needed.
 * @return A new buffer owned by the caller, or NULL if allocation failed.
 *         Free it with ctemplate_strbuf_destroy().
 */
CTEMPLATE_API ctemplate_strbuf *ctemplate_strbuf_create(size_t initial_capacity);

/**
 * @brief Destroy a buffer created with ctemplate_strbuf_create().
 *
 * Passing NULL is a no-op, mirroring free().
 */
CTEMPLATE_API void ctemplate_strbuf_destroy(ctemplate_strbuf *sb);

/**
 * @brief Append a NUL-terminated string to the buffer, growing it if needed.
 *
 * @param sb   Buffer to append to. Must not be NULL.
 * @param text NUL-terminated text to copy in. Must not be NULL.
 * @return CTEMPLATE_OK on success, CTEMPLATE_ERR_INVALID_ARG if sb or text
 *         is NULL, or CTEMPLATE_ERR_NOMEM if growing the buffer failed (the
 *         buffer is left unchanged in that case).
 */
CTEMPLATE_API ctemplate_status ctemplate_strbuf_append(ctemplate_strbuf *sb, const char *text);

/**
 * @brief Reset a buffer to the empty string without releasing its capacity.
 */
CTEMPLATE_API void ctemplate_strbuf_clear(ctemplate_strbuf *sb);

/**
 * @brief Borrow the buffer's contents as a NUL-terminated C string.
 *
 * The returned pointer is owned by @p sb: it is valid only until the next
 * mutating call (append/clear/destroy) on the same buffer, and must not be
 * freed by the caller.
 */
CTEMPLATE_API const char *ctemplate_strbuf_cstr(const ctemplate_strbuf *sb);

/** @brief Number of bytes currently stored, excluding the NUL terminator. */
CTEMPLATE_API size_t ctemplate_strbuf_length(const ctemplate_strbuf *sb);

#ifdef __cplusplus
}
#endif

#endif /* CTEMPLATE_CTEMPLATE_H */
